/**
 * Tweet Generation using Gemini AI
 * Generates wealth building and investing tweets dynamically
 */

import { generateTechTweet } from "./gemini.js";

// Cache for last generated tweet (to avoid duplicates)
let lastGeneratedTweet = null;

/**
 * Get a wealth building/investing tweet generated by Gemini AI
 * @param {string} theme - Optional theme for the tweet
 * @returns {Promise<string>} Generated tweet text
 */
export async function getRandomTweet(theme = "") {
  try {
    let tweetText = await generateTechTweet(theme);

    // Ensure we don't post the exact same tweet consecutively
    // If it matches, generate again (max 3 attempts to avoid infinite loop)
    let attempts = 0;
    while (tweetText === lastGeneratedTweet && attempts < 3) {
      console.log("[INFO] Generated duplicate tweet, generating new one...");
      tweetText = await generateTechTweet(theme);
      attempts++;
    }

    lastGeneratedTweet = tweetText;
    return tweetText;
  } catch (error) {
    console.error("[ERROR] Failed to generate tweet:", error.message);
    throw error;
  }
}
